# Generated by Django 4.1.4 on 2022-12-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(
                choices=[
                    ('ВН', 'В наличии'),
                    ('ПЗ', 'Под заказ'),
                    ('ОП', 'Ожидает поступления'),
                    ('НН', 'Нет в наличии'),
                    ('НП', 'Не производится'),
                ],
                default='ВН',
                max_length=2,
                verbose_name='Статус',
            ),
        ),
    ]
